version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reel_thumbnail
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - ./public/uploads:/app/public/uploads
    command: sh -c "mkdir -p /app/public/uploads && npm run dev"
    restart: unless-stopped 